SELECT 

"PUB"."STU-TS-TEST"."STUDENT-ID",
"PUB"."STU-TS-TEST"."STST-DATE-TAKEN",
"PUB"."STU-TS-TEST"."STST-ENTITY-ID",
"PUB"."STU-TS-TEST"."STST-SCHOOL-YEAR",
"PUB"."STU-TS-ELEMENT"."STSE-SCORE-DATA",
"PUB"."TEST-SCORE-ELEMENT"."TSEL-LDESC",
"PUB"."TEST-SCORE-NAME"."TEST-SCORE-NAME-LDESC"

FROM "PUB"."STUDENT-ENTITY"


LEFT  JOIN "PUB"."STU-TS-TEST"  ON "PUB"."STU-TS-TEST"."STUDENT-ID" = "PUB"."STUDENT-ENTITY"."STUDENT-ID"

LEFT JOIN "PUB"."STU-TS-ELEMENT" ON "PUB"."STU-TS-TEST"."STUDENT-ID" = "PUB"."STU-TS-ELEMENT"."STUDENT-ID"
AND "PUB"."STU-TS-TEST"."TEST-SCORE-TEST-ID"= "PUB"."STU-TS-ELEMENT"."TEST-SCORE-TEST-ID"
AND "PUB"."STU-TS-TEST"."STST-DATE-TAKEN" = "PUB"."STU-TS-ELEMENT"."STST-DATE-TAKEN"

LEFT JOIN "PUB"."TEST-SCORE-ELEMENT" ON "PUB"."STU-TS-ELEMENT"."TEST-SCORE-ELEMENT-ID" = "PUB"."TEST-SCORE-ELEMENT"."TEST-SCORE-ELEMENT-ID"

LEFT JOIN "PUB"."TEST-SCORE-TEST" ON "PUB"."STU-TS-ELEMENT"."TEST-SCORE-TEST-ID" = "PUB"."TEST-SCORE-TEST"."TEST-SCORE-TEST-ID"
LEFT JOIN "PUB"."TEST-SCORE-NAME" ON "PUB"."TEST-SCORE-TEST"."TEST-SCORE-NAME-ID" = "PUB"."TEST-SCORE-NAME"."TEST-SCORE-NAME-ID"

JOIN (
SELECT "PUB"."STU-TS-TEST"."STUDENT-ID", MAX ("PUB"."STU-TS-TEST"."STST-DATE-TAKEN") AS "test-date"
FROM "PUB"."STU-TS-TEST"
GROUP BY "PUB"."STU-TS-TEST"."STUDENT-ID") max_date
ON "PUB"."STU-TS-TEST"."STUDENT-ID" = max_date."STUDENT-ID" AND "PUB"."STU-TS-TEST"."STST-DATE-TAKEN" = max_date."test-date"

WHERE "PUB"."STUDENT-ENTITY"."STUDENT-STATUS" = 'A'
AND "PUB"."STUDENT-ENTITY"."X-DEFAULT-ENTITY" =1
AND "PUB"."TEST-SCORE-NAME"."TEST-SCORE-NAME-LDESC" = 'PSAT'
AND ("PUB"."TEST-SCORE-ELEMENT"."TSEL-LDESC" = 'S Reading and Writing'
OR "PUB"."TEST-SCORE-ELEMENT"."TSEL-LDESC" = 'S Math'
OR "PUB"."TEST-SCORE-ELEMENT"."TSEL-LDESC" = 'S Total Score'
)

